<div id="bottom-links">
	
    <div id="bottom-left">
            <div class="bottom-column-left column-one">
                <?php echo $this->getChildHtml("footer_links_contact_us")?>
            </div><!--bottom-column-left-->
            <div class="bottom-column-right column-two">
                <?php echo $this->getChildHtml("footer_links_customer_service")?>
            </div><!--bottom-column-right-->
            <div class="clr"></div>

            <div id="payment"><img alt="" src="<?php echo $this->getSkinUrl('images/payment.jpg');?>" /></div><!--payment-->							

    </div><!--bottom left-->

    <div id="bottom-right">
            <div class="bottom-column-left column-three">
                <?php echo $this->getChildHtml("footer_links_help_guides")?>
            </div><!--bottom-column-left-->

            <div class="bottom-column-right column-four">
                <?php echo $this->getChildHtml("footer_links_about_our_side")?>
            </div><!--bottom-column-right-->
            <div class="clr"></div>

    </div><!--bottom right-->
    <div class="clr"></div>

</div><!--bottom links-->