<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div id="box-slide-offer">	
    <h2 class="box-title"><?php echo $this->__('Our Bestsellers') ?></h2>
    
    <div class="previous-btn">
        <button name="previous" id="previous" type="button"><img alt="" src="<?php echo $this->getSkinUrl("images/prev-btn.jpg") ?>"/></button> 			
    </div>	
		
    <div class="next-btn">
        <button name="next" id="next" type="button"><img alt="" src="<?php echo $this->getSkinUrl("images/next-btn.jpg") ?>" /></button> 				
    </div>
		
    <div id="carouseldiv"> 
        <?php foreach ($_products as $_product): ?>
        <div class="set box-slide-product">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" width="85" height="85" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>		
            <h3 class="slider-product-title"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></h3>
            <p class="box-slide-description"><?php echo $this->stripTags($_product->getShortDescription(), null, true) ?></p>
            <?php echo $this->getPriceHtml($_product, true, '-widget-viewed-grid') ?>
        </div>	
        <?php endforeach; ?>
        <div class="clr"></div>		
    </div>
</div><!-- box-slide-offer -->
<?php endif; ?>